name: Build iOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: 7.3.0
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile

      - name: Setup Env Variables
        # grab the env vars from {secrets.GITHUB_ENV} and write them to the env file
        run: |
          echo "EXPO_PUBLIC_SUPABASE_URL=${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}" >> .env
          echo "EXPO_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env
          echo "VERCEL_URL=${{ secrets.VERCEL_URL }}" >> .env

      - name: Build
        run: |
          pnpm build:ios:local:non-interactive

      # zip the all the ipa files in the apps/expo/build-*.ipa
      - name: Zip ipa files
        run: |
          cd apps/expo
          zip -r build.zip build-*.ipa

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: apps/expo/build.zip

      - name: Zip the other files just in case
        run: |
          cd ~/work/
          zip -r other-files.zip *

      - name: Upload other files
        uses: actions/upload-artifact@v2
        with:
          name: other-files
          path: other-files.zip
