name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: 7.3.0
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile

      - name: Build
        run: |
          pnpm build:ios:local

      # zip the ./builds/ directory
      - name: Grab Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: ./builds/
